ECommerce.Web/Controllers/BarangController.cs
using ECommerce.Repo;
using ECommerce.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Web.Controllers
{
      public class BarangController : Controller
      {
            // GET: Barang
            public ActionResult Index()
            {
                  return View();
            }

            public ActionResult IndexCRUD()
            {
                  return View();
            }

            public ActionResult Create()
            {
                  List<VarianViewModel> varList = new List<VarianViewModel>() { new VarianViewModel() { Id = -1, Ukuran = "Pilih Ukuran" } };
                  varList.AddRange(VarianRepo.GetAll());
                  ViewBag.ListVarian = new SelectList(varList, "Id", "Ukuran");
                  return PartialView("_Create");
            }

            [HttpPost]
            public ActionResult Create(BarangViewModel model)
            {
                  if (ModelState.IsValid)
                  {
                        if (BarangRepo.Update(model))
                        {
                              return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                        }
                        else
                        {
                              return Json(new { success = false, message = BarangRepo.Message }, JsonRequestBehavior.AllowGet);
                        }
                  }

                  return Json(new { success = false, message = "Error invalid" }, JsonRequestBehavior.AllowGet);
            }

            public ActionResult List()
            {
                  return PartialView("_List", BarangRepo.GetAll());
            }

            public ActionResult ListCRUD()
            {
                  return PartialView("_ListCRUD", BarangRepo.GetAll());
            }
            public ActionResult Display(int id)
            {
                  List<VarianViewModel> varList = new List<VarianViewModel>() { new VarianViewModel() { Id = -1, Ukuran = "Pilih Ukuran" } };
                  varList.AddRange(VarianRepo.GetAll());
                  ViewBag.ListVarian = new SelectList(varList, "Id", "Ukuran");
                  return PartialView("_Display", BarangRepo.GetByItemId(id));
            }

            public ActionResult Edit(int id)
            {
                  BarangViewModel model = BarangRepo.GetByItemId(id);

                  List<VarianViewModel> varList = new List<VarianViewModel>() { new VarianViewModel() { Id = -1, Ukuran = "Pilih Ukuran" } };
                  varList.AddRange(VarianRepo.GetAll());
                  ViewBag.ListVarian = new SelectList(varList, "Id", "Ukuran");
                  return PartialView("_Edit", model);
            }

            [HttpPost]
            public ActionResult Edit(BarangViewModel model)
            {
                  if (ModelState.IsValid)
                  {
                        if (BarangRepo.Update(model))
                        {
                              return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                        }
                        else
                        {
                              return Json(new { success = false, message = BarangRepo.Message }, JsonRequestBehavior.AllowGet);
                        }
                  }

                  return Json(new { success = false, message = "Error invalid" }, JsonRequestBehavior.AllowGet);
            }

            public ActionResult Delete(int id)
            {
                  BarangViewModel model = BarangRepo.GetByItemId(id);
                  return PartialView("_Delete", model);
            }

            [HttpPost]
            public ActionResult DeleteConfirm(int id)
            {
                  if (BarangRepo.DeleteById(id))
                  {
                        return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                  }
                  else
                  {
                        return Json(new { success = false, message = BarangRepo.Message }, JsonRequestBehavior.AllowGet);
                  }
            }

      }
}

ECommerce.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeApp2.Web.Controllers
{
      public class HomeController : Controller
      {
            public ActionResult Index()
            {
                  return View();
            }

            public ActionResult About()
            {
                  ViewBag.Message = "Your application description page.";

                  return View();
            }

            public ActionResult Contact()
            {
                  ViewBag.Message = "Your contact page.";

                  return View();
            }

            public ActionResult Login()
            {
                  return PartialView("_Login");
            }
      }
}

ECommerce.Web/Controllers/KeranjangController.cs
using ECommerce.DataModel;
using ECommerce.Repo;
using ECommerce.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Web.Controllers
{
      public class KeranjangController : Controller
      {
            // GET: Keranjang
            public ActionResult Index()
            {
                  return View();
            }

            public ActionResult GetByItemId(int id)
            {
                  return PartialView("_GetByItemId", KeranjangRepo.GetByItemId(id));
            }
      }
}

ECommerce.Web/Controllers/VarianController.cs
using ECommerce.Repo;
using ECommerce.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Web.Controllers
{
      public class VarianController : Controller
      {
            // GET: Varian
            public ActionResult Index()
            {
                  return View();
            }

            public ActionResult List()
            {
                  return PartialView("_List", VarianRepo.GetAll());
            }

            public ActionResult Create()
            {
                  return PartialView("_Create");
            }

            [HttpPost]
            public ActionResult Create(VarianViewModel model)
            {
                  if (ModelState.IsValid)
                  {
                        if (VarianRepo.Update(model))
                        {
                              return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                        }
                        else
                        {
                              return Json(new { success = false, message = VarianRepo.Message }, JsonRequestBehavior.AllowGet);
                        }
                  }

                  return Json(new { success = false, message = "Error invalid" }, JsonRequestBehavior.AllowGet);
            }

            public ActionResult Edit(int id)
            {
                  VarianViewModel model = VarianRepo.GetByItemId(id);

                  return PartialView("_Edit", model);
            }

            [HttpPost]
            public ActionResult Edit(VarianViewModel model)
            {
                  if (ModelState.IsValid)
                  {
                        if (VarianRepo.Update(model))
                        {
                              return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                        }
                        else
                        {
                              return Json(new { success = false, message = BarangRepo.Message }, JsonRequestBehavior.AllowGet);
                        }
                  }

                  return Json(new { success = false, message = "Error invalid" }, JsonRequestBehavior.AllowGet);
            }

            public ActionResult Delete(int id)
            {
                  VarianViewModel model = VarianRepo.GetByItemId(id);
                  return PartialView("_Delete", model);
            }

            [HttpPost]
            public ActionResult DeleteConfirm(int id)
            {
                  if (VarianRepo.DeleteById(id))
                  {
                        return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                  }
                  else
                  {
                        return Json(new { success = false, message = VarianRepo.Message }, JsonRequestBehavior.AllowGet);
                  }
            }
      }
}

ECommerce.Web/Views/Barang/Index.cshtml
@{
    ViewBag.Title = "Index";
}

ECommerce.Web/Views/Barang/IndexCRUD.cshtml
@{
    ViewBag.Title = "CRUD Barang";
}
<div class="box">
    <div class="box-body">
        <div class="row">
            <div class="col-lg-12">
                <button type="button" id="btn-add" class="btn btn-success" title="Create New">Tambah Baru</button>
            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-lg-12" id="table-list">
                <h4>Loading...</h4>
            </div>
        </div>
    </div>
</div>
<div id="modal-form" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Modal title</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            ShowList();
        });

        function ShowList() {
            $.ajax({
                url: '@Url.Action("ListCRUD", "Barang")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result);
                }
            });
        }

        $("#btn-add").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "Barang")',
                type: 'get',
                success: function (result) {
                    $(".modal-title").html("Input Barang Baru");
                    $(".modal-body").html(result);
                    $("#modal-form").modal("show");
                }
            });
        });



    </script>
}

ECommerce.Web/Views/Barang/_Create.cshtml
@model ECommerce.ViewModel.BarangViewModel

@using (Html.BeginForm("Create", "Barang", FormMethod.Post, new { id = "create-form", name = "create-form" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Kode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PathGambar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PathGambar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PathGambar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamaBarang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamaBarang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NamaBarang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Varian_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Varian_Id, (IEnumerable<SelectListItem>)ViewBag.ListVarian, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Varian_Id, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Stok, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stok, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stok, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Harga, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Harga, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Harga, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#create-form").submit(function () {
        $.ajax({
            url: '@Url.Action("Create", "Barang")',
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#modal-form").modal("hide");
                    ShowList();
                } else {
                    alert('Error : ' + result.message);
                }
            }
        });
        return false;
    });
</script>

ECommerce.Web/Views/Barang/_Delete.cshtml
@model ECommerce.ViewModel.BarangViewModel

<h3>Apakah Anda yakin untuk menghapus ini?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PathGambar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PathGambar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NamaBarang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NamaBarang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VarianUkuran)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VarianUkuran)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stok)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stok)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="button" class="btn btn-danger btn-delete-confirm" data-id="@Model.Id">Delete</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
    }
</div>

<script type="text/javascript">
    $(".btn-delete-confirm").click(function () {
        $.ajax({
            url: '@Url.Action("DeleteConfirm", "Barang")',
            type: 'post',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                if (result.success) {
                    $("#modal-form").modal("hide");
                    ShowList();
                } else {
                    alert('Error : ' + result.message);
                }
            }
        });
    });
</script>

ECommerce.Web/Views/Barang/_Display.cshtml
@model ECommerce.ViewModel.BarangViewModel

<div>
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.NamaBarang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NamaBarang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VarianUkuran)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VarianUkuran)
            @*@Html.DropDownListFor(model => model.Varian_Id, (IEnumerable<SelectListItem>)ViewBag.ListVarian, new { @class = "form-control" })*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stok)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stok)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Harga)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Harga)
        </dd>

    </dl>
</div>
<p>
    <button type="button" class="btn btn-success btn-keranjang" data-dismiss="modal" title="Masukkan Ke Keranjang" data-id="@Model.Id">Masukkan Ke Keranjang</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal" title="Masukkan Ke Wishlist"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
</p>

<script type="text/javascript">
    $(".btn-keranjang").click(function () {
        var idx = $(this).attr("data-id");
        //alert(idx);
        $.ajax({
            url: '@Url.Action("ConfirmGet", "Barang")',
            type: 'post',
            data: { id: idx },
            success: function (result) {
                if (result.success) {
                    $.ajax({
                        url: '@Url.Action("KirimKeKeranjang", "Barang")',
                        type: 'post',
                        data: { id: idx },
                        success: function (result) {
                            if (result.success) {
                                alert('Pertama : ' + idx);
                                alert('Hasil : ' + result.message);
                                $("#modal-form").modal("hide");
                            } else {
                                alert('Error : ' + result.message);
                            }
                        }
                    });

                    alert('Kedua : ' + idx);
                    alert('Hasil : ' + result.message);
                    $("#modal-form").modal("hide");
                } else {
                    alert('Error : ' + result.message);
                }
            }
        });
    });
</script>

ECommerce.Web/Views/Barang/_Edit.cshtml
@model ECommerce.ViewModel.BarangViewModel


@using (Html.BeginForm("Edit", "Barang", FormMethod.Post, new { id = "edit-form", name = "edit-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Kode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PathGambar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PathGambar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PathGambar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamaBarang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamaBarang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NamaBarang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Varian_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Varian_Id, (IEnumerable<SelectListItem>)ViewBag.ListVarian, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Varian_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stok, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stok, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stok, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Harga, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Harga, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Harga, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#edit-form").submit(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Barang")',
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#modal-form").modal("hide");
                    ShowList();
                } else {
                    alert('Error : ' + result.message);
                }
            }
        });
        return false;
    });
</script>

ECommerce.Web/Views/Barang/_List.cshtml
@model IEnumerable<ECommerce.ViewModel.BarangViewModel>

<table class="table" id="data-list">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NamaBarang)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VarianUkuran)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PathGambar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Harga)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NamaBarang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VarianUkuran)
                </td>
                <td>
                    <img src="https://id-live-02.slatic.net/p/7/damai-atasan-basic-niki-stripe-konveksi-tanah-abang-1515727902-07432597-00eb55ea46f7d1ed3f63f52ce0105c01-catalog_233.jpg" alt="Chicago">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Harga)
                </td>
                <td>
                    <button type="button" class="btn btn-primary btn-display" data-id="@item.Id" title="Pilih Item">Pilih</button>
                </td>
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript">

    $("#data-list").DataTable();

    $(".btn-display").click(function () {
        $.ajax({
            url: '@Url.Action("Display", "Barang")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Detail Barang");
                $(".modal-body").html(result);
                $("#modal-form").modal("show");
            }
        });
    });


</script>

ECommerce.Web/Views/Barang/_ListCRUD.cshtml
@model IEnumerable<ECommerce.ViewModel.BarangViewModel>

<table class="table" id="data-list">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NamaBarang)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VarianUkuran)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PathGambar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Harga)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NamaBarang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VarianUkuran)
                </td>
                <td>
                    @Html.DisplayNameFor(model => model.PathGambar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Harga)
                </td>
                <td>
                    <button type="button" class="btn btn-warning btn-edit" data-id="@item.Id" title="Edit">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    </button>
                    <button type="button" class="btn btn-danger btn-delete" data-id="@item.Id" title="Delete">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript">
    $("#data-list").DataTable();

    $(".btn-edit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Barang")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Edit Barang");
                $(".modal-body").html(result);
                $("#modal-form").modal("show");
            }
        });
    });

    $(".btn-delete").click(function () {
        $.ajax({
            url: '@Url.Action("Delete", "Barang")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Hapus Barang");
                $(".modal-body").html(result);
                $("#modal-form").modal("show");
            }
        });
    });
</script>

ECommerce.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ECommerce.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ECommerce.Web/Views/Shared/_SidebarPartial.cshtml
<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu" style=" height: auto; overflow: hidden; width: auto; padding-bottom: 10%;">
            <li class="header"><strong>NAVIGASI UTAMA</strong></li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-paperclip"></i>
                    <span>Menu CRUD</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="@Url.Action("IndexCRUD", "Barang")">
                            <i class="fa fa-book"></i><span>Barang CRUD</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Varian")">
                            <i class="fa fa-book"></i><span>Varian CRUD</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-book"></i><span>Menu 1.3</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-paperclip"></i>
                    <span>Menu Pembeli</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="@Url.Action("Index", "Barang")">
                            <i class="fa fa-shopping-bag"></i><span>Barang</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Keranjang")">
                            <i class="fa fa-shopping-cart"></i><span>Keranjang</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-book"></i><span>Menu 1.3</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </section>
</aside>